stages:
  - build
  - update-helm-chart

variables:
  IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
  TAG_ONLY: $CI_COMMIT_SHORT_SHA
  CHART_REPO: github.com/NikolasEagle/moviecat-helm.git

workflow:
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
      changes:
        - "src/**/*"
        - "Dockerfile"
      when: always
    - if: $CI_COMMIT_BRANCH == "main"
      changes:
        - ".github/**/*"
        - "build/**/*"
        - "node_modules/**/*"
        - "public/**/*"
        - ".gitignore"
        - ".gitlab-ci.yml"
        - "LICENSE"
        - "package-lock.json"
        - "package.json"
        - "README.md"
      when: never
    - if: $CI_COMMIT_BRANCH == "main"
      when: always
    - when: never

build-task:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - >
      docker login $CI_REGISTRY
      -u $CI_REGISTRY_USER 
      -p $CI_REGISTRY_PASSWORD
  script:
    - docker build -t $IMAGE_TAG .
    - docker push $IMAGE_TAG

update-helm-chart-task:
  stage: update-helm-chart
  image: bitnami/git:latest
  variables:
    GIT_STRATEGY: none
  script:
    - git clone https://$CHART_REPO helm-charts
    - cd helm-charts/charts/moviecat
    - sed -i '/^frontend:/,/^[^ ]/ s/\(^[ ]*tag:\).*/\1 "'$TAG_ONLY'"/' values.yaml
    - awk '/^version:/ {split($2, v, "."); $2 = v[1]+1 "." v[2] "." v[3]} 1' Chart.yaml > Chart.yaml.tmp && mv Chart.yaml.tmp Chart.yaml
    - awk '/^appVersion:/ {split($2, v, "."); $2 = v[1] "." v[2]+1 "." v[3]} 1' Chart.yaml > Chart.yaml.tmp && mv Chart.yaml.tmp Chart.yaml
    - git config user.email "ci@gitlab.com"
    - git config user.name "GitLab CI"
    - git add .
    - git commit -m "Изменение версии образа для frontend на $TAG_ONLY"
    - git push https://${HELM_DEPLOY_USER}:${HELM_DEPLOY_TOKEN}@$CHART_REPO main
